# syntax=docker/dockerfile:1
ARG RUBY_VERSION=3.4.1
FROM ruby:$RUBY_VERSION-slim

# Rails app lives here
WORKDIR /myapp

# Install system packages
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      build-essential \
      libpq-dev \
      postgresql-client \
      nodejs \
      yarn \
      git \
      vim \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# Set development environment
ENV RAILS_ENV=development
ENV BUNDLE_WITHOUT="production"

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy application code
COPY . .

# Start server via bin/dev command by default, this can be overwritten at runtime
EXPOSE 3000
CMD ["bin/dev", "-b", "0.0.0.0"]
